
RGBLIGHT_ENABLE = yes #Enable WS2812 RGB underlight.
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

RGB_MATRIX_ENABLE = no
AUDIO_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
