#CONVERT_TO = elite_pi
#RGB_MATRIX_ENABLE = yes
#FP_TRACKBALL_ENABLE = yes
#AUDIO_ENABLE = yes
#ENCODER_ENABLE = yes

#ENCODER_MAP_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
USER_SONG_LIST = yes
#CONSOLE_ENABLE = yes
