#CONVERT_TO=elite_pi
#RGB_MATRIX_ENABLE = yes
#FP_TRACKBALL_ENABLE = yes
#AUDIO_ENABLE = yes
#ENCODER_ENABLE = yes

#TAP_DANCE_ENABLE = yes
#COMBO_ENABLE = yes
#USER_SONG_LIST = yes
#FP_DISABLE_CUSTOM_KEYCODES = yes
#FP_LAYER_LIGHTING_DISABLE = yes
#FP_LAYER_LIGHTING_DYNAMIC_BASE_LAYER_DISABLE = yes
CONSOLE_ENABLE = yes

